//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogsAnalyzerPFC.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("config\\pfc.config")]
        public string FicheroConfigPath {
            get {
                return ((string)(this["FicheroConfigPath"]));
            }
            set {
                this["FicheroConfigPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reports\\Templates.xlsx")]
        public string PlantillaInformesPath {
            get {
                return ((string)(this["PlantillaInformesPath"]));
            }
            set {
                this["PlantillaInformesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reports\\Reports.xlsx")]
        public string InformesPath {
            get {
                return ((string)(this["InformesPath"]));
            }
            set {
                this["InformesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reports\\PDFReport.pdf")]
        public string InformesPDFPath {
            get {
                return ((string)(this["InformesPDFPath"]));
            }
            set {
                this["InformesPDFPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reports.xlsx")]
        public string ReportFileName {
            get {
                return ((string)(this["ReportFileName"]));
            }
            set {
                this["ReportFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PDFReport.pdf")]
        public string PDFReportFileName {
            get {
                return ((string)(this["PDFReportFileName"]));
            }
            set {
                this["PDFReportFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("files")]
        public string FilesPath {
            get {
                return ((string)(this["FilesPath"]));
            }
            set {
                this["FilesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int MaxInitialCommands {
            get {
                return ((int)(this["MaxInitialCommands"]));
            }
            set {
                this["MaxInitialCommands"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int MaxCommandsUsed {
            get {
                return ((int)(this["MaxCommandsUsed"]));
            }
            set {
                this["MaxCommandsUsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int MaxParams {
            get {
                return ((int)(this["MaxParams"]));
            }
            set {
                this["MaxParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("files\\Manual.pdf")]
        public string ManualPath {
            get {
                return ((string)(this["ManualPath"]));
            }
            set {
                this["ManualPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("external_resources\\ReportsResources")]
        public string ExternalResources {
            get {
                return ((string)(this["ExternalResources"]));
            }
            set {
                this["ExternalResources"] = value;
            }
        }
    }
}
