//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogsAnalyzerPFC.entidades.messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogsAnalyzerPFC.entidades.messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicación Realizada como Proyecto de Fin de Carrera.
        ///
        ///Tiene como finalidad principal ayudar al usuario en el análisis de un fichero de logs capturado con la herramienta Snoopy.
        ///
        ///Autor: María Yolanda González Castillo.
        ///
        ///Tutor: Alejandro Calderón Mateos
        ///
        ///Año de Creación: 2015.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimado amigo,
        ///
        ///Tengo el placer de enviarle los informes solicitados.
        ///
        ///No dude en volver a utilizar la aplicación para futuros análisis.
        ///
        ///Un saludo,
        ///
        ///El Equipo de Desarrollo.
        /// </summary>
        internal static string BodyMail {
            get {
                return ResourceManager.GetString("BodyMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen datos para el Informe solicitado; Cambie las opciones de filtrado y vuelva a intentarlo..
        /// </summary>
        internal static string EMPTY {
            get {
                return ResourceManager.GetString("EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excepción.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error guardando los informes. Compruebe, por favor, que hay espacio en disco y vuelva a intentarlo..
        /// </summary>
        internal static string ErrorCopyFolder {
            get {
                return ResourceManager.GetString("ErrorCopyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para poder realizar el análisis de un fichero log, debe cargar previamente un fichero de comandos iniciales con la lógica del análisis..
        /// </summary>
        internal static string ErrorMsgCommandsFile {
            get {
                return ResourceManager.GetString("ErrorMsgCommandsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error exportando el fichero Excel a PDF. Por favor, cierre los ficheros abiertos y vuelva a intentarlo..
        /// </summary>
        internal static string ErrorMsgExportFailed {
            get {
                return ResourceManager.GetString("ErrorMsgExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe actualmente ningún fichero de logs cargado en la base de datos. Para poder realizar un informe, debe cargar previamente uno..
        /// </summary>
        internal static string ErrorMsgLogFile {
            get {
                return ResourceManager.GetString("ErrorMsgLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error durante el envio del mensaje. Por favor, compruebe que todo está todo correcto, y vuelva a intentarlo..
        /// </summary>
        internal static string ErrorMsgMailSent {
            get {
                return ResourceManager.GetString("ErrorMsgMailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible realizar el análisis sobre el fichero de logs proporcionado puesto que no existe ningún comando cargado en la base de datos. Por favor, inserte un fichero de comandos iniciales y vuelva a intentarlo de nuevo..
        /// </summary>
        internal static string ErrorMsgNoCommands {
            get {
                return ResourceManager.GetString("ErrorMsgNoCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe ningún fichero de logs almacenado en la base de datos. Por favor, cargue uno e intenténtelo de nuevo..
        /// </summary>
        internal static string ErrorMsgNoLogFile {
            get {
                return ResourceManager.GetString("ErrorMsgNoLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para poder realizar un informe, debe cargar previamente el fichero de comandos iniciales con los comandos y categorias con la lógica del análisis..
        /// </summary>
        internal static string ErrorMsgNoOldCommands {
            get {
                return ResourceManager.GetString("ErrorMsgNoOldCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para poder realizar un informe, debe cargar previamente el fichero de logs que quiere analizar..
        /// </summary>
        internal static string ErrorMsgNoOldFile {
            get {
                return ResourceManager.GetString("ErrorMsgNoOldFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para poder realizar un análisis correcto, es imprescindible que cargue previamente tanto el fichero de comandos iniciales como el fichero de logs que quiere analizar..
        /// </summary>
        internal static string ErrorMsgNoReport {
            get {
                return ResourceManager.GetString("ErrorMsgNoReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay informes para realizar. La tabla de Informes de la base de datos está vacía. Inserte alguno, y vuelva a intentarlo..
        /// </summary>
        internal static string ErrorReports {
            get {
                return ResourceManager.GetString("ErrorReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error al borrar los datos de comandos y usuarios de la base de datos..
        /// </summary>
        internal static string FileTreatmentErrorDeletingPreviousData {
            get {
                return ResourceManager.GetString("FileTreatmentErrorDeletingPreviousData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error al almacenar los comandos nuevos en la base de datos..
        /// </summary>
        internal static string FileTreatmentErrorLoadingNewCommands {
            get {
                return ResourceManager.GetString("FileTreatmentErrorLoadingNewCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error al almacenar los usuarios en la base de datos..
        /// </summary>
        internal static string FileTreatmentErrorLoadingUsers {
            get {
                return ResourceManager.GetString("FileTreatmentErrorLoadingUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error leyendo el fichero de logs..
        /// </summary>
        internal static string FileTreatmentErrorReadingFile1pass {
            get {
                return ResourceManager.GetString("FileTreatmentErrorReadingFile1pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error leyendo el fichero de logs..
        /// </summary>
        internal static string FileTreatmentErrorReadingFile2pass {
            get {
                return ResourceManager.GetString("FileTreatmentErrorReadingFile2pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error al recuperar el listado de comandos..
        /// </summary>
        internal static string FileTreatmentErrorRetrievingAllCommands {
            get {
                return ResourceManager.GetString("FileTreatmentErrorRetrievingAllCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error al recuperar el listado de usuarios..
        /// </summary>
        internal static string FileTreatmentErrorRetrievingAllUsers {
            get {
                return ResourceManager.GetString("FileTreatmentErrorRetrievingAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error al almacenar los comandos nuevos pendientes en la base de datos..
        /// </summary>
        internal static string FileTreatmentErrorSavingPendingCommands {
            get {
                return ResourceManager.GetString("FileTreatmentErrorSavingPendingCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione la categoría por la que desea filtrar los informes:.
        /// </summary>
        internal static string FilterTypeCategoryMessage {
            get {
                return ResourceManager.GetString("FilterTypeCategoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el comando por el que desea filtrar los informes:.
        /// </summary>
        internal static string FilterTypeCommandMessage {
            get {
                return ResourceManager.GetString("FilterTypeCommandMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el usuario por el que desea filtrar los informes:.
        /// </summary>
        internal static string FilterTypeUserMessage {
            get {
                return ResourceManager.GetString("FilterTypeUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione la carpeta donde desea guardar los informes..
        /// </summary>
        internal static string FolderDialog {
            get {
                return ResourceManager.GetString("FolderDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea borrar la información existente en la base de datos?.
        /// </summary>
        internal static string InfoMsgClearDB {
            get {
                return ResourceManager.GetString("InfoMsgClearDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea cargar un fichero nuevo de comandos iniciales?.
        /// </summary>
        internal static string InfoMsgCommandsFile {
            get {
                return ResourceManager.GetString("InfoMsgCommandsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea cargar un fichero de logs nuevo para analizar?.
        /// </summary>
        internal static string InfoMsgLogFile {
            get {
                return ResourceManager.GetString("InfoMsgLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El mensaje ha sido enviado correctamente..
        /// </summary>
        internal static string InfoMsgMailSent {
            get {
                return ResourceManager.GetString("InfoMsgMailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Quiere analizar el fichero de logs que acaba de cargar con la lógica del fichero de comandos iniciales que nos ha proporcionado?.
        /// </summary>
        internal static string InfoMsgMakeReport {
            get {
                return ResourceManager.GetString("InfoMsgMakeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Quiere analizar el fichero de logs que nos ha proporcionado con la lógica que hay almacenada en la base de datos?.
        /// </summary>
        internal static string InfoMsgOldCommands {
            get {
                return ResourceManager.GetString("InfoMsgOldCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Quiere realizar un análisis de los logs almacenados actualmente en la base de datos, con la lógica cargada recientemente?.
        /// </summary>
        internal static string InfoMsgOldLogs {
            get {
                return ResourceManager.GetString("InfoMsgOldLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea realizar un análisis de la información almacenada en la base de datos?.
        /// </summary>
        internal static string InfoMsgOldReport {
            get {
                return ResourceManager.GetString("InfoMsgOldReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea realizar un análisis del fichero de logs cargado recientemente?.
        /// </summary>
        internal static string InfoMsgReport {
            get {
                return ResourceManager.GetString("InfoMsgReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe generado correctamente..
        /// </summary>
        internal static string InfoMsgReportOk {
            get {
                return ResourceManager.GetString("InfoMsgReportOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarea finalizada correctamente..
        /// </summary>
        internal static string InfoMsgTaskOk {
            get {
                return ResourceManager.GetString("InfoMsgTaskOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha seleccionado ninguna carpeta destino donde guardar el informe generado. Por favor, vuelva a intentarlo y seleccione la ubicación donde quiere guardarlo..
        /// </summary>
        internal static string InfoNoFolder {
            get {
                return ResourceManager.GetString("InfoNoFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha seleccionado ninguna opción para el informe. Por favor, seleccione al menos una de ellas y vuelva a intentarlo..
        /// </summary>
        internal static string InfoNoFormat {
            get {
                return ResourceManager.GetString("InfoNoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generando PDF.
        /// </summary>
        internal static string InfoPDFCreator {
            get {
                return ResourceManager.GetString("InfoPDFCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error recuperando la informacion del excel de comandos y categorias. Compruebe el formato del fichero de entrada..
        /// </summary>
        internal static string InitialChargeErrorReadingExcelFile {
            get {
                return ResourceManager.GetString("InitialChargeErrorReadingExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error al almacenar las categorías en la base de datos..
        /// </summary>
        internal static string InitialChargeErrorSavingCategories {
            get {
                return ResourceManager.GetString("InitialChargeErrorSavingCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error al almacenar los comandos en la base de datos..
        /// </summary>
        internal static string InitialChargeErrorSavingCommands {
            get {
                return ResourceManager.GetString("InitialChargeErrorSavingCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string MessageBoxCancel {
            get {
                return ResourceManager.GetString("MessageBoxCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string MessageBoxNo {
            get {
                return ResourceManager.GetString("MessageBoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        internal static string MessageBoxOk {
            get {
                return ResourceManager.GetString("MessageBoxOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        internal static string MessageBoxYes {
            get {
                return ResourceManager.GetString("MessageBoxYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviando correo electrónico....
        /// </summary>
        internal static string MsgMailSendingStatus {
            get {
                return ResourceManager.GetString("MsgMailSendingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error aplicando los filtros seleccionados..
        /// </summary>
        internal static string MsgUpdateReportFiltersError {
            get {
                return ResourceManager.GetString("MsgUpdateReportFiltersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicando filtros....
        /// </summary>
        internal static string MsgUpdateReportFiltersInit {
            get {
                return ResourceManager.GetString("MsgUpdateReportFiltersInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se han aplicado los filtros correctamente..
        /// </summary>
        internal static string MsgUpdateReportFiltersOk {
            get {
                return ResourceManager.GetString("MsgUpdateReportFiltersOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to categoría.
        /// </summary>
        internal static string ReportGenerateCategoryFilterMsg {
            get {
                return ResourceManager.GetString("ReportGenerateCategoryFilterMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comando.
        /// </summary>
        internal static string ReportGenerateCommandFilterMsg {
            get {
                return ResourceManager.GetString("ReportGenerateCommandFilterMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrado por.
        /// </summary>
        internal static string ReportGenerateFilteredByMsg {
            get {
                return ResourceManager.GetString("ReportGenerateFilteredByMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usuario.
        /// </summary>
        internal static string ReportGenerateUserFilterMsg {
            get {
                return ResourceManager.GetString("ReportGenerateUserFilterMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Borrados Correctamente..
        /// </summary>
        internal static string ReportProgress_B {
            get {
                return ResourceManager.GetString("ReportProgress_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrando Categorías....
        /// </summary>
        internal static string ReportProgress_BC {
            get {
                return ResourceManager.GetString("ReportProgress_BC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrando Comandos Iniciales....
        /// </summary>
        internal static string ReportProgress_BCI {
            get {
                return ResourceManager.GetString("ReportProgress_BCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrando datos....
        /// </summary>
        internal static string ReportProgress_BD {
            get {
                return ResourceManager.GetString("ReportProgress_BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrando Resgistros Log Almacenados....
        /// </summary>
        internal static string ReportProgress_BL {
            get {
                return ResourceManager.GetString("ReportProgress_BL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrando Usuarios....
        /// </summary>
        internal static string ReportProgress_BU {
            get {
                return ResourceManager.GetString("ReportProgress_BU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichero de Logs Cargado Correctamente..
        /// </summary>
        internal static string ReportProgress_C1 {
            get {
                return ResourceManager.GetString("ReportProgress_C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichero de Comandos Iniciales Cargado Correctamente..
        /// </summary>
        internal static string ReportProgress_C2 {
            get {
                return ResourceManager.GetString("ReportProgress_C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando Categorias....
        /// </summary>
        internal static string ReportProgress_CC {
            get {
                return ResourceManager.GetString("ReportProgress_CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando Comandos Iniciales....
        /// </summary>
        internal static string ReportProgress_CCI {
            get {
                return ResourceManager.GetString("ReportProgress_CCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando Datos....
        /// </summary>
        internal static string ReportProgress_CD {
            get {
                return ResourceManager.GetString("ReportProgress_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobando Informes Solicitados....
        /// </summary>
        internal static string ReportProgress_CI {
            get {
                return ResourceManager.GetString("ReportProgress_CI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando Registros Log....
        /// </summary>
        internal static string ReportProgress_CL {
            get {
                return ResourceManager.GetString("ReportProgress_CL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando Usuarios y Comandos Nuevos....
        /// </summary>
        internal static string ReportProgress_CUyC {
            get {
                return ResourceManager.GetString("ReportProgress_CUyC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generando el Informe Solicitado....
        /// </summary>
        internal static string ReportProgress_GIS {
            get {
                return ResourceManager.GetString("ReportProgress_GIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiando Base de Datos....
        /// </summary>
        internal static string ReportProgress_LBD {
            get {
                return ResourceManager.GetString("ReportProgress_LBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leyendo el Fichero de Comandos Iniciales....
        /// </summary>
        internal static string ReportProgress_LFCI {
            get {
                return ResourceManager.GetString("ReportProgress_LFCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizando Informe....
        /// </summary>
        internal static string ReportProgress_RI {
            get {
                return ResourceManager.GetString("ReportProgress_RI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizando Informes Solicitados....
        /// </summary>
        internal static string ReportProgress_RIS {
            get {
                return ResourceManager.GetString("ReportProgress_RIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error borrando la información previa de la base de datos..
        /// </summary>
        internal static string RestartDataBaseErrorDeletingPreviousData {
            get {
                return ResourceManager.GetString("RestartDataBaseErrorDeletingPreviousData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informes de la Aplicación PFC.
        /// </summary>
        internal static string SubjectMail {
            get {
                return ResourceManager.GetString("SubjectMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertencia.
        /// </summary>
        internal static string Warn {
            get {
                return ResourceManager.GetString("Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para poder generar un nuevo informe, por favor, cierre el informe anterior o guárdelo en otra carpeta..
        /// </summary>
        internal static string WarnFileOpened {
            get {
                return ResourceManager.GetString("WarnFileOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar al menos un tipo de informe a generar..
        /// </summary>
        internal static string WarnMsgChooseReport {
            get {
                return ResourceManager.GetString("WarnMsgChooseReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha seleccionado ningún fichero de comandos iniciales para cargar. Los informes se realizarán con los comandos y categorías existentes en la base de datos..
        /// </summary>
        internal static string WarnMsgCommandsFile {
            get {
                return ResourceManager.GetString("WarnMsgCommandsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha seleccionado ningún fichero de logs nuevo para analizar. Los informes se realizarán con la información existente en la base de datos..
        /// </summary>
        internal static string WarnMsgLogFile {
            get {
                return ResourceManager.GetString("WarnMsgLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe introducir una dirección de correo electrónico válida..
        /// </summary>
        internal static string WarnMsgMailAddress {
            get {
                return ResourceManager.GetString("WarnMsgMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error borrando los datos almacenados..
        /// </summary>
        internal static string WorkerErrorDeletingData {
            get {
                return ResourceManager.GetString("WorkerErrorDeletingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error cargando el fichero de logs proporcionado..
        /// </summary>
        internal static string WorkerErrorFileTreatment {
            get {
                return ResourceManager.GetString("WorkerErrorFileTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error generando el informe solicitado..
        /// </summary>
        internal static string WorkerErrorGeneratingReport {
            get {
                return ResourceManager.GetString("WorkerErrorGeneratingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error cargando el fichero de comandos iniciales..
        /// </summary>
        internal static string WorkerErrorRestartDB {
            get {
                return ResourceManager.GetString("WorkerErrorRestartDB", resourceCulture);
            }
        }
    }
}
